name: CustomMobs
version: '${project.version}'
main: com.kaguya.custommobs.CustomMobsPlugin
api-version: '1.20'
author: kaguya-prj

commands:
  cmob:
    description: Custom Mob管理コマンド
    usage: /cmob spawn <mobId> [x y z] [world] | /cmob reload | /cmob list | /cmob cleanup [mobId] | /cmob tame | /cmob release | /cmob build <listingId> | /cmob mypets | /cmob claim
    permission: custommobs.command

permissions:
  custommobs.command:
    description: /cmob コマンドを使用できる
    default: op
